name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo dckr_pat_93Gmlsc7J3WqEfengsPqLLEm_fU | docker login -u nessimntambiw --password-stdin

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nessimntambiw/kmscfrontend:latest
          build-args: |
            NODE_ENV=production
