name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo dckr_pat_vCXYV5EysQD0vu9Q-pDSJhp1W98 | docker login -u abelyusufa --password-AbelYusuf@123

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ssentamuabel/kmscfrontend:latest
          build-args: |
            NODE_ENV=production
